### ISSUE TITLE
Temp file wallpaper.bmp

### ISSUE THREAD

**Issue by gituncar** [genzj/pybingwallpaper#47]
Hi if possible move to temp location wallpaper.bmp, and keep only .jpg file on real output path location.
file wallpaper.bmp, or delete after download files bing.

**Comment by genzj** [comment]
The `wallpaper.bmp` is not generated during downloading. It's actually required by Windows when setting a jpeg as wallpaper. I don't know how things are exactly going after win10 era, but per my experiments Windows doesn't support using jpeg files directly for wallpaper. That's why I use PIL to convert them to the `wallpaper.bmp`. You won't see it in Linux or download-only mode (remove the bmp then rerun with `--setter=no`).

move it to another directory might be a good solution, except for deciding which folder it belongs to... I really have no idea about this, after all pybingwallpaper is running across multiple platforms.

May I ask why you want to get rid of it? maybe we can come up with a quick solution for the expected results.

Thanks a lot for asking.
